name: Bump app version based on PR labels

on:
  pull_request:
    branches:
    - dev
    # types:
    #   - closed

jobs:
  setup_dart_and_run_converter:
    runs-on: ubuntu-latest
    outputs:
      parts: ${{ steps.labels_to_version_parts.outputs.parts }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Convert labels to version parts
        id: labels_to_version_parts
        run: "dart labels_to_version_parts.dart ${{ join(github.event.pull_request.labels.*.name,' ') }}"
    
  bump_version_based_on_labels:
    if: ${{ (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    needs: setup_dart_and_run_converter
    steps:
    # Setup Ruby, Bundler, Gemfile & flutter dependencies & Build Android
    - name: Setup Fastlane
      uses: ruby/setup-ruby@72d59482210349c1114eca714b6c5df19fbbec34
      with:
        ruby-version: "2.6"
        bundler-cache: true
        working-directory: android
    - run: bundle exec fastlane bump_version push:true branch:${{ github.ref_name }} bump:${{needs.setup_dart_and_run_converter.outputs.parts}} tag:false
      working-directory: android
