name: CI Dev

on:
  pull_request:
    branches:
    - dev

jobs:
  analyze_code_and_test:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    outputs:
      parts: ${{ steps.labels_to_version_parts.outputs.parts }}
    steps:
    # Checkout Repo code
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
    - name: Get flutter dependencies.
      run: flutter pub get

    - name: Check for any formatting issues in the code.
      run: flutter format --set-exit-if-changed .

    - name: Statically analyze the Dart code for any errors.
      run: flutter analyze ./lib

    - name: Run Test
      run: flutter test

    - name: Convert labels to version parts
      id: labels_to_version_parts
      run: "dart labels_to_version_parts.dart join(github.event.pull_request.labels.*.name,' ')"
    
  bump_version_based_on_labels:
    if: ${{ (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    needs: analyze_code_and_test
    steps:
    # Setup Ruby, Bundler, Gemfile & flutter dependencies & Build Android
    - name: Setup Fastlane
      uses: ruby/setup-ruby@72d59482210349c1114eca714b6c5df19fbbec34
      with:
        ruby-version: "2.6"
        bundler-cache: true
        working-directory: android
    - run: bundle exec fastlane bump_version push:true branch:${{ github.ref_name }} bump:${{needs.analyze_code_and_test.outputs.parts}} tag:false
      working-directory: android
