name: CD Stable
on:
  # Enable manual run 
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - promote
          - deploy
      bump_version:
        description: "Fastlane Bump version"
        required: true
        default: "bump_version"
        type: choice
        options:
          - build
          - patch
          - minor
          - major
      track:
        description: "Deploy to"
        required: true
        default: "alpha"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
      promote_from:
        description: "Promote from"
        required: true
        default: "alpha"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
      promote_to:
        description: "Promote to"
        required: true
        default: "beta"
        type: choice
        options:
          - production
          - beta
          - alpha
          - internal
permissions: read-all
jobs:
  # build_web:
  #   name: Build Flutter (Web)
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: subosito/flutter-action@v1
  #     with:
  #         channel: 'stable'
  #   - run: flutter pub get
  #   - run: flutter config --enable-web
  #   - run: flutter build web
  #   - name: Archive Production Artifact
  #     uses: actions/upload-artifact@master
  #     with:
  #       name: web-build
  #       path: build/web

  # deploy_web:
  #   name: Deploy Web to Firebase Hosting
  #   needs: build_web
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@master
  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: web-build
  #         path: web-build
  #     - name: Deploy to Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting --public web-build
  #       env:
  #         GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  #         PROJECT_ID: default

  fastlane-build-deploy-android:
    name: Deploy Android Release to Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v
      # Checkout Repo code
      - name: Checkout Repo
        uses: actions/checkout@v3
      # Setup Ruby, Bundler, Gemfile & flutter dependencies & Build Android
      - name: Setup Fastlane
        uses: ruby/setup-ruby@72d59482210349c1114eca714b6c5df19fbbec34
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - run: cd android; bundle exec fastlane bump_version bump:${{ github.event.inputs.bump_version || 'build' }}
      - run: cd android; bundle exec fastlane android deploy track:${{ github.event.inputs.track || 'beta' }}
        if: ${{ github.event.inputs.lane == 'deploy' }}
      - run: cd android; bundle exec fastlane android promote from:${{ github.event.inputs.promote_from || 'alpha' }} to:${{ github.event.inputs.promote_to || 'beta' }}
        if: ${{ github.event.inputs.lane == 'promote' }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android